const $=id=>document.getElementById(id),today=new Date(),fields=['product','audience','value','proof'];
const sloganLines=[['王老吉','怕上火，喝王老吉','怕上火｜预防上火｜怕/喝押节奏｜直接喝'],['步步高点读机','哪里不会点哪里','不会｜一点就会｜重复“哪里”｜直接点'],['士力架','横扫饥饿，做回自己','饥饿｜快速顶饿｜前后反差｜吃一根'],['瓜子二手车','没有中间商赚差价','买贵卖亏｜没有差价｜口语直白｜上平台'],['OPPO','充电五分钟，通话两小时','没电｜快速充电｜数字反差｜立即充'],['脑白金','今年过节不收礼，收礼只收脑白金','送礼难｜礼品选择｜重复洗脑｜直接买'],['小葵花','孩子咳嗽老不好，多半是肺热','孩子咳嗽｜对症清肺热｜像医生提醒｜对症选'],['铂爵旅拍','想去哪拍，就去哪拍','婚照单一｜边旅行边拍｜重复“去哪”｜马上选'],['作业帮','作业有问题，就上作业帮','不会做｜快速解题｜问题/作业帮｜直接上'],['王饱饱','好吃不胖，王饱饱','怕胖｜低负担好吃｜好吃/饱饱押韵｜直接吃']];
const briefs=[{product:'清泉水',audience:'怕白水没味的人',value:'自然回甘',proof:'森林水源'},{product:'清火凉茶',audience:'爱吃辣的人',value:'吃辣不上火',proof:'草本配方'},{product:'一生印记婚戒',audience:'准备求婚的人',value:'故事刻进戒指',proof:'可刻指纹'},{product:'小耳朵点读笔',audience:'小学生家长',value:'一点就会',proof:'8000词句'},{product:'行家说',audience:'职场新人',value:'真人经验解答',proof:'职业认证'},{product:'醒一醒冷萃',audience:'怕苦的上班族',value:'提神不苦',proof:'12小时冷萃'},{product:'满格能量棒',audience:'忙到没空吃饭的人',value:'快速顶饿',proof:'10克蛋白质'},{product:'多一格收纳架',audience:'租房青年',value:'不打孔收纳',proof:'承重20公斤'},{product:'续航饮料',audience:'控糖熬夜的人',value:'零糖提神',proof:'80毫克咖啡因'},{product:'本真面霜',audience:'敏感肌',value:'温和修护',proof:'无酒精香精'}];
const tvcLines=[['苹果《老唱片》','深夜，女孩翻出父亲的旧唱片。镜头切回童年，父亲牵着她跳舞。如今她用手机录下父亲笨拙的舞步。时间会走远，爱不会。','用物件串起时间与亲情'],['支付宝《账单》','一张张账单闪过：第一份工资、第一次远行、第一次给妈妈转账。数字记下消费，也记下你认真生活的每一天。','让功能数据承载人生故事'],['耐克《再跑一步》','清晨五点，城市还没醒。有人系紧鞋带，有人擦掉汗水。冠军不是站上领奖台的人，是每次想停下时，又多跑一步的人。','用行动递进建立品牌精神'],['宜家《晚餐》','桌子不大，菜也普通。孩子把最后一块肉夹给奶奶，爸爸偷偷加了一把椅子。家不在面积里，在愿意坐在一起的人里。','从生活细节抵达品牌价值'],['美团《赶得上》','雨落下来，骑手穿过街巷。办公室里的一碗热汤，医院门口的一袋药，都有人在等。你需要的，我们努力让它赶得上。','多个场景汇成服务承诺'],['小米《第一张照片》','他不懂构图，只把镜头对准刚出生的女儿。十年后，女儿用同一部相册拍下他的白发。影像不必完美，重要的是没有错过。','以时间反转制造情感落点'],['蒙牛《草原的一天》','太阳升起前，牧场已经醒了。从一棵草到一杯奶，要经过几十道检验。你喝到的简单，是我们守住的复杂。','把生产证据转译成安心'],['滴滴《回家》','最后一班地铁已经开走。加班的人、值夜班的护士、刚下飞机的旅客，仍在奔向同一个方向：家。再晚，也有人送你回去。','同一目的连接不同人物'],['华为《连接》','海岛教师打开屏幕，千里外的课堂同时亮起。技术不是让距离消失，而是让远方的人不再缺席。','让技术功能升华为社会价值'],['京东《快一点》','快一点送到，是为了生日蜡烛点亮之前；快一点换新，是为了工作别被打断。快，不是数字，是不耽误每个重要时刻。','用具体场景解释速度价值']];
const longLines=[['江小白《表达瓶》','有些话，到了嘴边又咽下去。我们总以为来日方长，却把“谢谢”“对不起”和“我想你”留到太晚。一杯酒解决不了沉默，但可以给真心一个开口的机会。今晚，和想见的人坐下来，把没说的话慢慢说完。','从人群洞察进入产品场景'],['方太《油烟情书》','厨房里的爱，很少大声说出来。它藏在清晨六点的那碗面里，藏在等你回家才开火的灶台旁，也藏在一个人默默擦掉的油烟里。我们认真研究每一次吸排，只想让做饭的人少闻一点油烟，多留一点好心情。','用细节将技术与关怀连接'],['网易云音乐《评论》','你戴上耳机，不一定是为了隔绝世界。有时只是想给情绪找一个不被打断的地方。有人在同一首歌下写下失恋，有人写下重逢。陌生人的故事没有替你解决问题，却让你知道，此刻并不是只有你一个人。','共同情绪构成平台价值'],['招商银行《时间银行》','年轻时，我们用时间换钱；后来才发现，最想买回来的也是时间。陪父母吃顿饭，看孩子慢慢长大，给自己一个没有会议的下午。理财不是只让数字增加，而是让未来的你，多一点选择时间的自由。','重定义品类利益'],['SK-II《她最后去了相亲角》','如果年龄是一张标签，谁有权替你贴上？二十岁要漂亮，三十岁要结婚，四十岁要安稳。每一个“应该”，都可能遮住你真正想要的人生。你不必按别人的时间表抵达幸福。人生，从来没有统一答案。','冲突开篇并表达品牌立场'],['Keep《自律不是命令》','不是每一次训练都要刷新纪录。今天比昨天多走一千步，累的时候仍愿意伸展十分钟，也是在向更好的自己靠近。自律不是惩罚身体，而是学会认真照顾它。现在开始，不必完美，只需完成。','降低行动门槛'],['OPPO《留下这一刻》','孩子第一次叫妈妈，父母第一次来看你的城市，朋友在毕业那天笑得东倒西歪。重要的时刻不会提前通知你。我们把影像做得更清楚，不是为了参数更漂亮，而是当多年以后想念发生，你仍能看清那天每个人的脸。','参数服务于记忆'],['蚂蚁森林《一棵树》','手机里轻轻一点，远方真的会多一片绿色吗？一份能量很小，一棵树也很小。但当千万次坚持落在同一片土地上，沙开始停下，鸟重新回来。改变世界不一定要做惊天动地的事，也可以从今天少开一次车开始。','疑问开场，以证据推动行动'],['褚橙《人生总有起落》','他曾站在高处，也曾从头开始。七十多岁承包荒山，等一棵橙树结果，要花六年。时间没有给他捷径，却把酸甜慢慢酿进果肉。人生总有起落，精神终可传承。','人物故事映射产品口感'],['天猫《理想生活》','理想生活不是一张标准答案。有人想住进更大的房子，有人只想把阳台变成花园；有人追赶潮流，有人珍惜旧物。真正的理想，不是拥有别人羡慕的生活，而是每天都更接近自己喜欢的样子。','从多元场景建立品牌包容性']];
const modes={slogan:{name:'Slogan',items:sloganLines,max:40,min:4,ideal:[6,16],title:'看完10条，再连续写3版。',place:['先写直觉版本，不要反复修改。','换一个角度，突出价值或痛点。','再压缩一次，尝试更强的节奏。'],checks:['哪一句3秒就记住','哪一句价值最清楚','哪一句最想念出来','哪一句最想让人行动']},tvc:{name:'TVC广告',items:tvcLines,max:500,min:60,ideal:[90,260],title:'仿写一支30秒TVC：画面、旁白、收束。',place:['写出场景和人物，再推进冲突。','换一种叙事结构，强化情绪转折。','精简旁白，让品牌在结尾自然出现。'],checks:['开头哪个画面抓住你','故事如何发生转折','产品价值如何进入情节','结尾如何留下品牌']},long:{name:'长文案',items:longLines,max:1200,min:120,ideal:[180,700],title:'仿写一篇长文案：洞察、展开、落点。',place:['从真实场景或人群洞察开篇。','换一个结构，让价值和证据逐步出现。','删掉空话，写出更有力量的结尾。'],checks:['开头为什么想继续读','洞察是否说中了人','证据是否支撑承诺','结尾是否完成升华或行动']}};
let mode='slogan',dailyIndex=Math.floor(today.getTime()/86400000)%10,daily=briefs[dailyIndex];
$('day').textContent=`DAY ${String(today.getDate()).padStart(2,'0')} · 今日训练`;
function records(){return JSON.parse(localStorage.getItem('slogan-attempts')||'[]')}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderMode(){const m=modes[mode];document.body.dataset.mode=mode;document.querySelectorAll('.mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('reading-label').textContent=`01 / 今日10条${m.name}语感输入`;$('practice-title').textContent=m.title;m.checks.forEach((x,i)=>$('check'+(i+1)).textContent=x);$('case-list').innerHTML=m.items.map((x,i)=>`<article class="case-row"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${esc(x[1])}</strong><small>${esc(x[0])} · ${esc(x[2])}</small></div></article>`).join('');fields.forEach(id=>$(id).value=daily[id]);['draft1','draft2','draft3'].forEach((id,i)=>{$(id).value='';$(id).maxLength=m.max;$(id).placeholder=m.place[i]});$('result').hidden=true;$('improve-panel').hidden=true;ready()}
document.querySelectorAll('.mode-tabs button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderMode()});
function stats(){const r=records();$('average').textContent=r.length?Math.round(r.reduce((a,x)=>a+x.score,0)/r.length):'—';$('count').textContent=r.length?`已完成 ${r.length} 次训练`:'完成第一次训练后生成';const days=new Set(r.map(x=>x.date));let streak=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}$('streak').textContent=streak}
function includesAny(s,text){return text.split(/[，。；、\s]/).filter(x=>x.length>=2).some(w=>s.includes(w))}
function evaluate(s){const m=modes[mode],n=s.length;let score=100,p=[],good=[];if(n<m.min){score-=25;p.push(`${n}字太短，${m.name}需要完整表达，建议至少写到${m.min}字。`)}else if(n>m.ideal[1]){score-=10;p.push(`目前${n}字，信息偏散。删除重复句，把篇幅控制在${m.ideal[1]}字左右。`)}else good.push('篇幅能承载当前训练目标。');if(!includesAny(s,daily.value)){score-=20;p.push('核心价值没有被清楚表达。读完仍不知道产品究竟带来什么不同。')}else good.push('产品价值已进入表达，不只是情绪或口号。');if(!includesAny(s,daily.proof)){score-=12;p.push('缺少具体证据，承诺还停留在自说自话。')}else good.push('使用了事实或产品细节，可信度更高。');if(mode==='slogan'){if(n>16){score-=14;p.push('Slogan超过16字，三秒读取和复述都会变难。')}if(!/[，！？、]/.test(s)&&n>10){score-=7;p.push('缺少口语停顿，读起来发平。')}if(!/(喝|吃|选|来|用|买|试|点|让|给|就)/.test(s)){score-=9;p.push('缺少动作或明确结果，更像介绍，不像广告语。')}else good.push('有动作或结果，具备传播推动力。')}else if(mode==='tvc'){if(!/(清晨|深夜|镜头|画面|此刻|突然|后来|多年|这时|最后)/.test(s)){score-=12;p.push('没有清晰的画面推进或时间变化，旁白像一段说明文字。')}else good.push('有可拍摄的场景与叙事推进。');if(!/(却|但是|直到|原来|不是|而是|终于|没想到)/.test(s)){score-=10;p.push('故事没有转折，情绪从头到尾是一条直线。')}if(!/(最后|于是|从此|现在|让|我们|品牌|今天)/.test(s)){score-=8;p.push('结尾缺少品牌收束或行动落点。')}}else{if(!/[？?]/.test(s)&&!/(有些|我们|你是否|当你|不是每|曾经)/.test(s)){score-=10;p.push('开头缺少问题、场景或洞察，第一段抓力不足。')}else good.push('开头具备洞察或阅读钩子。');if(!/[。！？]\s*\n/.test(s)&&n>220){score-=8;p.push('全文没有分段，阅读压力大；按洞察、展开、证据、结尾重新分层。')}if(!/(所以|但是|其实|直到|因为|不是|而是|也许|真正)/.test(s)){score-=9;p.push('观点缺少递进或转折，像把几句话并排放在一起。')}else good.push('表达有递进，能带着读者向结论前进。')}score=Math.max(20,Math.min(98,score));return{score,verdict:score>=90?'成熟，已接近可发布':score>=80?'方向正确，但还能更锋利':score>=65?'基本成立，结构和表达仍有明显问题':'不合格，建议按反馈重写',problems:p.slice(0,4),strengths:good.slice(0,3)}}
function ready(){$('submit').disabled=!['draft1','draft2','draft3'].some(id=>$(id).value.trim())}
['draft1','draft2','draft3'].forEach(id=>$(id).addEventListener('input',ready));
$('submit').onclick=()=>{const drafts=['draft1','draft2','draft3'].map((id,i)=>({text:$(id).value.trim(),version:i+1})).filter(x=>x.text),results=drafts.map(x=>({...x,...evaluate(x.text)})),best=results.slice().sort((a,b)=>b.score-a.score)[0],all=records();results.forEach(x=>all.push({...daily,...x,slogan:x.text,mode,date:new Date().toISOString().slice(0,10)}));localStorage.setItem('slogan-attempts',JSON.stringify(all));$('score').textContent=best.score;$('verdict').textContent=best.verdict;$('draft-scores').innerHTML=results.map(x=>`<article><span>版本${x.version}</span><strong>${esc(x.text)}</strong><b>${x.score}分</b><small>${x.verdict}</small></article>`).join('');$('problems').innerHTML=best.problems.map((p,i)=>`<p><b>${i+1}</b>${p}</p>`).join('')||'<p>没有明显硬伤，继续打磨语言的独特性。</p>';$('strengths').innerHTML=best.strengths.map(p=>`<p>✓ ${p}</p>`).join('');$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth'});stats()};
$('rewrite').onclick=()=>{$('result').hidden=true;$('draft1').focus()};
function samples(){if(mode==='slogan')return [`${daily.value.split('，')[0]}，就选${daily.product.split('「')[0]}`,`${daily.product}：${daily.value}`,`${daily.proof}，让${daily.value}`];if(mode==='tvc')return [`清晨，主人公正被问题困住。镜头跟随他的动作，直到${daily.product}出现。${daily.value}。因为${daily.proof}。生活没有突然变容易，但他终于能从容向前。`, `三个不同的人，在三个不同地点面对同一种难题。他们不约而同选择${daily.product}。${daily.proof}，带来${daily.value}。真正的改变，发生在每一个普通时刻。`,`多年后，他仍记得那一天的细节，却忘了当时有多难。因为${daily.product}让${daily.value}。${daily.proof}。把复杂留给我们，把从容还给生活。`];return [`有些麻烦看起来很小，却每天都在消耗我们。对${daily.audience}来说，真正需要的不是更多选择，而是一次确定的解决。${daily.product}带来${daily.value}，并以${daily.proof}让承诺可以被相信。少一点将就，多一点从容，从今天开始。`,`我们习惯把问题忍过去，直到它一次次打断生活。其实，好的产品不是制造新的欲望，而是认真解决一个旧问题。${daily.product}理解${daily.audience}：${daily.value}。这不是一句漂亮话，${daily.proof}。当复杂被妥善处理，生活才能把时间还给真正重要的事。`,`什么才是值得选择的产品？不是声音最大，而是把承诺做成看得见的细节。${daily.product}为${daily.audience}而来，以${daily.proof}，实现${daily.value}。我们相信，每一个被认真对待的小问题，最终都会变成生活里真实的轻松。`]}
$('improve').onclick=()=>{const labels=['约90分：补齐核心结构','约95分：价值与证据更自然','冲刺100分：观点与落点更独特'];$('improve-panel').innerHTML='<h3>高分改写示范</h3><p class="improve-intro">不要直接抄。对照你的版本，看它怎样补上结构、证据与落点。</p>'+samples().map((x,i)=>`<article><span>${labels[i]}</span><strong>${esc(x)}</strong></article>`).join('');$('improve-panel').hidden=false;$('improve-panel').scrollIntoView({behavior:'smooth'})};
function renderHistory(){const names={slogan:'Slogan',tvc:'TVC广告',long:'长文案'},all=records().slice().reverse();$('history-list').innerHTML=all.length?all.map(x=>`<article class="history-item"><div class="history-score">${x.score}<small>分</small></div><div><p class="history-meta">${x.date} · ${names[x.mode]||'Slogan'} · ${esc(x.product||'未填写产品')}</p><h3>${esc(x.text||x.slogan)}</h3><p>${x.verdict}</p></div></article>`).join(''):'<div class="history-empty">还没有训练记录。完成今天的第一次训练吧。</div>'}
$('history-open').onclick=()=>{renderHistory();$('history').hidden=false;$('history').scrollIntoView({behavior:'smooth'})};$('history-close').onclick=()=>{$('history').hidden=true;window.scrollTo({top:0,behavior:'smooth'})};
renderMode();stats();

