const cases=[
{brand:'农夫山泉',line:'农夫山泉有点甜',note:'用可感知的味觉利益建立记忆，短、具体、有产品关联。',product:'山泉饮用水「清泉」',audience:'不喜欢白水寡淡、重视天然口感的上班族',value:'入口有自然回甘，比普通饮用水更有味道',proof:'水源来自国家级森林保护区'},
{brand:'王老吉',line:'怕上火，喝王老吉',note:'痛点与解决方案直接相连，形成清晰购买指令。',product:'植物凉茶「清火一号」',audience:'爱吃烧烤火锅、担心上火的年轻人',value:'畅快吃辣，减少上火负担',proof:'沿用传统草本配方，0脂肪'},
{brand:'戴比尔斯',line:'钻石恒久远，一颗永流传',note:'把产品特性翻译成情感价值，表达有节奏。',product:'定制婚戒「一生印记」',audience:'准备求婚、希望礼物独一无二的情侣',value:'把两个人的故事永久刻进戒指',proof:'支持专属指纹与纪念日镌刻'},
{brand:'步步高点读机',line:'哪里不会点哪里',note:'一句话演示产品怎么用，功能利益一眼可见。',product:'儿童英语点读笔「小耳朵」',audience:'想让孩子自主学英语、没时间陪读的家长',value:'孩子不会的单词自己一点就能学',proof:'覆盖小学阶段8000个核心词句'},
{brand:'知乎',line:'有问题，就会有答案',note:'清楚回答平台为用户带来的核心利益。',product:'职场问答社区「行家说」',audience:'刚工作、遇到问题却没人可问的职场新人',value:'快速获得真实从业者的经验答案',proof:'回答者均完成职业身份认证'},
{brand:'麦斯威尔',line:'滴滴香浓，意犹未尽',note:'感官利益加余韵，让产品体验可以被想象。',product:'冷萃咖啡「醒一醒」',audience:'午后犯困但不喜欢苦咖啡的办公室人群',value:'清醒提神，同时口感顺滑不苦涩',proof:'低温萃取12小时，添加糖为0'},
{brand:'士力架',line:'横扫饥饿，做回自己',note:'把饥饿痛点戏剧化，并给出清晰结果。',product:'坚果能量棒「满格」',audience:'来不及吃饭、需要快速补充能量的通勤者',value:'迅速缓解饥饿，保持工作状态',proof:'每根含10克蛋白质和三种坚果'},
{brand:'宜家',line:'让日常生活更美好',note:'从产品功能上升到用户的日常生活价值。',product:'免打孔收纳架「多一格」',audience:'居住空间小、东西多又不想打孔的租房青年',value:'不伤墙面，也能多出整齐收纳空间',proof:'承重20公斤，安装仅需3分钟'},
{brand:'红牛',line:'你的能量，超乎你想象',note:'将功能利益转化为充满画面的能量感。',product:'无糖能量饮料「续航」',audience:'需要熬夜赶进度、又在控制糖分的创意工作者',value:'快速恢复专注，同时没有糖分负担',proof:'0糖，每罐含80毫克咖啡因'},
{brand:'多芬',line:'真实的美',note:'用价值观重新定义品类，形成品牌立场。',product:'敏感肌面霜「本真」',audience:'皮肤敏感、厌倦复杂护肤步骤的女性',value:'温和修护，让皮肤回到稳定自然状态',proof:'无香精无酒精，通过敏感肌测试'},
{brand:'Airbnb',line:'四海为家',note:'把住宿功能提升为到任何地方都有归属感。',product:'长住公寓平台「住进来」',audience:'异地工作一个月以上、希望像本地人生活的人',value:'短租也能拥有完整、自在的家居生活',proof:'所有房源均配备厨房、洗衣机和独立工作区'},
{brand:'佳能',line:'感动常在',note:'不讲设备参数，直接占据记录情感的价值。',product:'口袋打印机「留一张」',audience:'喜欢记录聚会旅行、习惯用手机拍照的年轻人',value:'把手机里的瞬间立即变成可触摸的照片',proof:'无需墨盒，连接手机后30秒打印'}];
const upgrades=[['每一口，都有山泉回甘','清泉，喝得到的自然回甘','清泉入喉，山野回甘'],['吃辣尽兴，清火随行','放心吃辣，就喝清火一号','辣得尽兴，火不上身'],['把两个人的故事戴一生','一枚婚戒，刻下两个人的一生','把一生，刻进这一枚'],['不会的单词，点一下就会','孩子自己点，英语自己会','哪里不会，自己点会'],['职场难题，来问行家','不懂就问，答案来自真行家','职场每一问，都有过来人'],['清醒不必苦，冷萃醒一醒','醒得快，也可以不苦','十二小时冷萃，一口清醒不苦'],['十克蛋白，迅速赶走饥饿','饿了来一根，状态马上满格','一根满格，把饥饿清零'],['不打孔，也能多一格','三分钟多一格，墙面不留痕','墙上不留痕，生活多一格'],['续上专注，不续糖','零糖续航，专注满格','糖分清零，专注续航'],['温和修护，敏感少一点','少一点刺激，多一点稳定','本真面霜，让敏感回归稳定'],['短住一个月，也像回到家','住进来，不只是住下来','走到哪里，都能住进生活里'],['手机里的瞬间，30秒拿在手里','30秒，把感动留在手上','手机里的感动，马上留一张']];
const $=id=>document.getElementById(id),today=new Date(),daily=cases[Math.floor(today.getTime()/86400000)%cases.length],fields=['product','audience','value','proof','slogan'];$('day').textContent=`DAY ${String(today.getDate()).padStart(2,'0')} · 今日训练`;$('case-line').textContent=`“${daily.line}”`;$('case-brand').textContent=daily.brand;$('case-note').textContent=daily.note;['product','audience','value','proof'].forEach(id=>$(id).value=daily[id]);
function records(){return JSON.parse(localStorage.getItem('slogan-attempts')||'[]')}function stats(){const r=records();$('average').textContent=r.length?Math.round(r.reduce((a,x)=>a+x.score,0)/r.length):'—';$('count').textContent=r.length?`已完成 ${r.length} 次训练`:'完成第一次训练后生成';const days=new Set(r.map(x=>x.date));let streak=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}$('streak').textContent=streak}stats();
function evaluate(f){const s=f.slogan.trim();let score=100,p=[],good=[],generic=['品质','匠心','美好','精彩','未来','专业','卓越','领先','选择','生活'],words=f.value.split(/[，。；、\s]/).filter(x=>x.length>=2),proof=f.proof.split(/[，。；、\s]/).filter(x=>x.length>=2);if(s.length>16){score-=18;p.push(`句子有 ${s.length} 个字，太长。三秒内读不完，先删到 12 字左右。`)}else if(s.length<4){score-=10;p.push('太短，但没有形成完整意思。短不是目的，记得住的价值才是。')}else good.push('长度控制合格，具备快速读取的基础。');if(!f.value){score-=18;p.push('你没有填写“独特价值”，评分无法判断这句话到底在卖什么利益。')}else if(!words.some(w=>s.includes(w))){score-=24;p.push('没有说清独特价值。用户看完仍不知道“它能给我什么”。')}else good.push('核心利益进入了广告语，不是在空喊品牌态度。');if(f.proof&&!proof.some(w=>s.includes(w))){score-=12;p.push('缺少可信证据。你的承诺没有被产品、工艺、销量或事实支撑。')}const hits=generic.filter(w=>s.includes(w));if(hits.length&&!words.some(w=>s.includes(w))){score-=14;p.push(`“${hits.join('、')}”是泛词，竞品也能说。现在这句话没有品牌专属性。`)}if(!/[，！？、]/.test(s)&&s.length>10){score-=7;p.push('句子没有停顿和节奏，朗读起来发平，记忆点弱。')}else good.push('有明确的口语节奏或停顿。');if(!/(喝|吃|选|来|用|买|试|点|上|让|给|就|要)/.test(s)){score-=10;p.push('没有动作指令。它更像一句介绍，不像能推动选择的广告语。')}else good.push('包含动作或结果，具备一定购买推动力。');if(!f.product){score-=6;p.push('你没有填写产品或品牌，无法进行“换牌测试”。')}else if(s.includes(f.product))good.push('品牌/产品与表达有绑定，不容易被完全替换。');else{score-=8;p.push('换成竞品名字仍然成立。品牌绑定不够，容易替别人做广告。')}score=Math.max(18,Math.min(96,score));return{score,verdict:score>=85?'可用，但还可以再狠一点':score>=70?'方向对，表达还不够锋利':score>=55?'有想法，但现在还不是广告语':'不合格，建议推倒重写',problems:p.slice(0,3),strengths:good.slice(0,3)}}
function ready(){$('submit').disabled=!$('slogan').value.trim()}$('slogan').addEventListener('input',()=>{$('chars').textContent=`${$('slogan').value.length}/40`;ready()});$('submit').onclick=()=>{const f=Object.fromEntries(fields.map(id=>[id,$(id).value.trim()])),r=evaluate(f),all=records();all.push({...f,...r,date:new Date().toISOString().slice(0,10)});localStorage.setItem('slogan-attempts',JSON.stringify(all));$('score').textContent=r.score;$('verdict').textContent=r.verdict;$('problems').innerHTML=r.problems.map((x,i)=>`<p><b>${i+1}</b>${x}</p>`).join('');$('strengths').innerHTML=r.strengths.map(x=>`<p>✓ ${x}</p>`).join('');$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth'});stats()};$('rewrite').onclick=()=>{$('result').hidden=true;$('slogan').focus()};
$('improve').onclick=()=>{const set=upgrades[cases.indexOf(daily)],labels=['约90分：价值更清楚','约95分：节奏与品牌绑定更强','冲刺100分：表达更独特'];$('improve-panel').innerHTML='<h3>高分改写示范</h3><p class="improve-intro">不要直接抄。对照你的原句，看它们分别补上了什么。</p>'+set.map((x,i)=>`<article><span>${labels[i]}</span><strong>${x}</strong></article>`).join('');$('improve-panel').hidden=false;$('improve-panel').scrollIntoView({behavior:'smooth'})};
function renderHistory(){const all=records().slice().reverse();$('history-list').innerHTML=all.length?all.map((x,i)=>`<article class="history-item"><div class="history-score">${x.score}<small>分</small></div><div><p class="history-meta">${x.date} · ${x.product||'未填写产品'}</p><h3>${x.slogan}</h3><p>${x.verdict}</p></div></article>`).join(''):'<div class="history-empty">还没有训练记录。完成今天的第一条广告语吧。</div>'}$('history-open').onclick=()=>{renderHistory();$('history').hidden=false;$('history').scrollIntoView({behavior:'smooth'})};$('history-close').onclick=()=>{$('history').hidden=true;window.scrollTo({top:0,behavior:'smooth'})};

